GymManagement/GymManagement/Controllers/ContactController.cs
using System.Web.Mvc;

namespace YourApp.Controllers
{
    public class ContactController : Controller
    {
        // Hiển thị trang liên hệ
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        // Xử lý gửi thông tin liên hệ
        [HttpPost]
        public ActionResult Send(string Name, string Email, string Message)
        {
            // TODO: xử lý gửi email hoặc lưu vào database

            TempData["Success"] = "Cảm ơn bạn đã liên hệ! Chúng tôi sẽ phản hồi sớm.";
            return RedirectToAction("Index");
        }
    }
}

GymManagement/GymManagement/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GymManagement.Controllers
{

    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GymManagement/GymManagement/Controllers/MemberController.cs
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity; // dùng EntityState
using GymManagement.Models;
using GymManagement.Filters;

namespace GymManagement.Controllers
{
    [AuthorizeRole("Admin")]
    public class MemberController : Controller
    {
        private GymDbContext db = new GymDbContext();

        // GET: Member
        public ActionResult Index()
        {
            // Load cả thông tin gói tập khi hiển thị danh sách
            var members = db.Members.Include(m => m.Package).ToList();
            return View(members);
        }

        // GET: Member/Details/5
        public ActionResult Details(int id)
        {
            var member = db.Members.Include(m => m.Package).FirstOrDefault(m => m.ID == id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // GET: Member/Create
        public ActionResult Create()
        {
            ViewBag.PackageId = new SelectList(db.Packages.ToList(), "Id", "Name");
            return View();
        }

        // POST: Member/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Member member)
        {
            if (ModelState.IsValid)
            {
                db.Members.Add(member);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            // Nếu lỗi, hiển thị lại dropdown
            ViewBag.PackageId = new SelectList(db.Packages.ToList(), "Id", "Name", member.PackageId);
            return View(member);
        }

        // GET: Member/Edit/5
        public ActionResult Edit(int id)
        {
            var member = db.Members.Find(id);
            if (member == null)
            {
                return HttpNotFound();
            }

            ViewBag.PackageId = new SelectList(db.Packages.ToList(), "Id", "Name", member.PackageId);
            return View(member);
        }

        // POST: Member/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Member member)
        {
            if (ModelState.IsValid)
            {
                db.Entry(member).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PackageId = new SelectList(db.Packages.ToList(), "Id", "Name", member.PackageId);
            return View(member);
        }

        // GET: Member/Delete/5
        public ActionResult Delete(int id)
        {
            var member = db.Members.Include(m => m.Package).FirstOrDefault(m => m.ID == id);
            if (member == null)
            {
                return HttpNotFound();
            }
            return View(member);
        }

        // POST: Member/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var member = db.Members.Find(id);
            if (member != null)
            {
                db.Members.Remove(member);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

GymManagement/GymManagement/Controllers/PackagesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using GymManagement.Filters;
using GymManagement.Models;

namespace GymManagement.Controllers
{
   
    public class PackagesController : Controller
    {
        private GymDbContext db = new GymDbContext();

        // GET: Package
        public ActionResult Index()
        {
            return View(db.Packages.ToList());
        }

        // GET: Package/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Package package = db.Packages.Find(id);
            if (package == null)
            {
                return HttpNotFound();
            }
            return View(package);
        }

        // GET: Package/Create
        [AuthorizeRole("Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Package/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Price,Duration")] Package package)
        {
            if (ModelState.IsValid)
            {
                db.Packages.Add(package);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(package);
        }

        // GET: Package/Edit/5
        [AuthorizeRole("Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Package package = db.Packages.Find(id);
            if (package == null)
            {
                return HttpNotFound();
            }
            return View(package);
        }

        // POST: Package/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Price,Duration")] Package package)
        {
            if (ModelState.IsValid)
            {
                db.Entry(package).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(package);
        }

        // GET: Package/Delete/5
        [AuthorizeRole("Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Package package = db.Packages.Find(id);
            if (package == null)
            {
                return HttpNotFound();
            }
            return View(package);
        }

        // POST: Package/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Package package = db.Packages.Find(id);
            db.Packages.Remove(package);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

GymManagement/GymManagement/Controllers/TrainerController.cs
using System.Linq;
using System.Web.Mvc;
using GymManagement.Models;
using System.Data.Entity;
using GymManagement.Filters;


namespace GymManagement.Controllers
{
   
   
    public class TrainerController : Controller
    {
        private GymDbContext db = new GymDbContext();

        // GET: Trainer
        public ActionResult Index()
        {
            var trainers = db.Trainers.ToList();
            return View(trainers);
        }
        [AuthorizeRole("Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Trainer/Create
        [HttpPost]
        [AuthorizeRole("Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                db.Trainers.Add(trainer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trainer);
        }
        // GET: Trainer/Edit/5
        [AuthorizeRole("Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var trainer = db.Trainers.Find(id);
            if (trainer == null)
                return HttpNotFound();

            return View(trainer);
        }

        // POST: Trainer/Edit/5
        [HttpPost]
        [AuthorizeRole("Admin")]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(trainer);
        }
        // GET: Trainer/Delete/5
        [AuthorizeRole("Admin")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var trainer = db.Trainers.Find(id);
            if (trainer == null)
                return HttpNotFound();

            return View(trainer);
        }

        // POST: Trainer/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var trainer = db.Trainers.Find(id);
            db.Trainers.Remove(trainer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        // GET: Trainer/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var trainer = db.Trainers.Find(id);
            if (trainer == null)
                return HttpNotFound();

            return View(trainer);
        }


    }
}

GymManagement/GymManagement/Controllers/TrialController.cs
using System.Linq;
using System.Web.Mvc;
using GymManagement.Models;

namespace GymManagement.Controllers
{
    public class TrialController : Controller
    {
        private GymDbContext db = new GymDbContext();

        // GET: Trial/Register
        public ActionResult Register()
        {
            ViewBag.PackageId = new SelectList(db.Packages, "Id", "Name");
            return View();
        }

        // POST: Trial/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(TrialRegistration trial)
        {
            if (ModelState.IsValid)
            {
                db.TrialRegistrations.Add(trial);
                db.SaveChanges();
                TempData["Success"] = "Cảm ơn bạn đã đăng ký tập thử! Chúng tôi sẽ liên hệ sớm nhất.";
                return RedirectToAction("Register");
            }

            ViewBag.PackageId = new SelectList(db.Packages, "Id", "Name", trial.PackageId);
            return View(trial);
        }
    }
}

GymManagement/GymManagement/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GymManagement/GymManagement/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GymManagement/GymManagement/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang Chủ";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Hero Section (Jumbotron đầu trang) -->
<marquee behavior="scroll" direction="left" class="bg-dark text-white py-2 font-weight-bold"> 💥 Chào mừng bạn đến với Phòng Gym của chúng tôi! Cùng luyện tập, nâng cao sức khỏe và chinh phục vóc dáng mơ ước! 💪 </marquee>
<div class="jumbotron jumbotron-fluid text-white position-relative overflow-hidden" style="background-image: url('https://dungcutheduc.vn/images/contents/fitness.jpg'); background-size: cover; background-position: center; height: 500px;">
    <div class="overlay" style="position:absolute; top:0; left:0; width:100%; height:100%; background-color: rgba(0,0,0,0.5); z-index:1;"></div>
    <div class="container h-100 d-flex flex-column justify-content-center align-items-start position-relative" style="z-index:2;">
        <h1 class="display-4 font-weight-bold animate__animated animate__fadeInDown">💪 Sẵn sàng thay đổi vóc dáng?</h1>
        <p class="lead animate__animated animate__fadeInUp delay-1s">Tham gia tập thử miễn phí ngay hôm nay và trải nghiệm phòng Gym hiện đại cùng huấn luyện viên chuyên nghiệp.</p>

        <div class="d-flex flex-wrap mt-3 animate__animated animate__fadeInUp delay-2s">
            <a class="btn btn-outline-light btn-lg mr-3 mb-2" href="@Url.Action("Index", "Packages")"><i class="fas fa-dumbbell mr-1"></i> Gói Tập</a>
            <a class="btn btn-outline-light btn-lg mr-3 mb-2" href="@Url.Action("Index", "Contact")"><i class="fas fa-envelope mr-1"></i> Liên hệ</a>
            <a class="btn btn-warning btn-lg mb-2" href="@Url.Action("Register", "Trial")"><i class="fas fa-user-plus mr-1"></i> Đăng ký Ngay</a>
        </div>
    </div>

</div>

<!-- Carousel hình ảnh -->
<div class="container mb-5">
    <div id="gymCarousel" class="carousel slide" data-ride="carousel" data-interval="3000">
        <ol class="carousel-indicators">
            <li data-target="#gymCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#gymCarousel" data-slide-to="1"></li>
            <li data-target="#gymCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner rounded shadow">
            <div class="carousel-item active">
                <img src="~/Content/Images/gym6.jpg" class="d-block w-100" style="height: 500px; object-fit: cover;" alt="Gym 1" />
            </div>
            <div class="carousel-item">
                <img src="~/Content/Images/gym7.jpg" class="d-block w-100" style="height: 500px; object-fit: cover;" alt="Gym 2" />
            </div>
            <div class="carousel-item">
                <img src="~/Content/Images/gym8.jpg" class="d-block w-100" style="height: 500px; object-fit: cover;" alt="Gym 3" />
            </div>
            <div class="carousel-item">
                <img src="~/Content/Images/gym5.jpg" class="d-block w-100" style="height: 500px; object-fit: cover;" alt="Gym 4" />
            </div>
        </div>
        <a class="carousel-control-prev" href="#gymCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </a>
        <a class="carousel-control-next" href="#gymCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon"></span>
        </a>
    </div>
</div>

<!-- Giới thiệu -->
<div class="container text-center mt-5">
    <h2>Vì sao chọn chúng tôi?</h2>
    <p class="text-muted">Phòng gym hiện đại, huấn luyện viên chuyên nghiệp, môi trường thân thiện.</p>
</div>

<!-- Các chức năng -->
<div class="container text-center mt-5">
    <h2>Chức năng chính</h2>
    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card shadow-sm h-100">
                <div class="card-body">
                    <h5 class="card-title">Thành viên</h5>
                    <p class="card-text">Thêm, sửa, xóa và quản lý danh sách thành viên.</p>
                    <a href="@Url.Action("Index", "Member")" class="btn btn-outline-primary">Xem chi tiết</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mt-3 mt-md-0">
            <div class="card shadow-sm h-100">
                <div class="card-body">
                    <h5 class="card-title">Huấn luyện viên</h5>
                    <p class="card-text">Quản lý danh sách các huấn luyện viên chuyên nghiệp.</p>
                    <a href="@Url.Action("Index", "Trainer")" class="btn btn-outline-primary">Xem chi tiết</a>
                </div>
            </div>
        </div>
        <div class="col-md-4 mt-3 mt-md-0">
            <div class="card shadow-sm h-100">
                <div class="card-body">
                    <h5 class="card-title">Gói tập</h5>
                    <p class="card-text">Tạo và chỉnh sửa các gói tập phù hợp với từng người dùng.</p>
                    <a href="@Url.Action("Index", "Packages")" class="btn btn-outline-primary">Xem chi tiết</a>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Liên hệ -->
<div class="container mt-5">
    <h2 class="text-center">Liên hệ với chúng tôi</h2>

    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success text-center mt-3">@TempData["Success"]</div>
    }

    <div class="row justify-content-center mt-4">
        <div class="col-md-8">
            <form method="post" action="@Url.Action("Send", "Contact")">
                <div class="form-group">
                    <label for="Name">Họ và tên</label>
                    <input type="text" class="form-control" id="Name" name="Name" required />
                </div>
                <div class="form-group">
                    <label for="Email">Email</label>
                    <input type="email" class="form-control" id="Email" name="Email" required />
                </div>
                <div class="form-group">
                    <label for="Message">Nội dung</label>
                    <textarea class="form-control" id="Message" name="Message" rows="5" required></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Gửi liên hệ</button>
            </form>
        </div>
    </div>
</div>

<!-- Chân trang -->
<footer class="bg-dark text-white text-center py-4 mt-5">
    <div class="container">
        <p class="mb-1">&copy; 2025 Phòng Gym KhoaPug. All rights reserved.</p>
        <p class="mb-0">
            <i class="fas fa-map-marker-alt mr-2"></i> 123 Đường Gym, Quận Liên Chiểu, Đà Nẵng |
            <i class="fas fa-phone-alt ml-3 mr-2"></i> 0909 999 999 |
            <i class="fas fa-envelope ml-3 mr-2"></i> info@gymdanang.vn
        </p>
    </div>
</footer>